services:
  - type: web
    name: churn-prediction-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: JWT_SECRET_KEY
        value: bf3a53c48c82814907d354c9494dd82af01b640e6bb080fdba8be73e3a7aee2f
      - key: PORT
        value: 10000
  - type: web
    name: ml-service
    runtime: python
    rootDir: ml-service
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10001
